<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'http://');
define('WP_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/plugins');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '200M');




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db4979552107');
define('DB_USER', 'fw6328388273');
define('DB_PASSWORD', 'vdFVCJoJfkYnVKRCmqLmwsJVFT4nVD');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'wp_6qblbfyfus_';


/****************************************************************************/
/*                          Plugin Configuration                            */
/****************************************************************************/




/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          'm@6_Sn!P`]5WLh4FTBS&pXz:-7irsV;>+w0np,u{6mTjA1b*bF0QfQ(=Z=io0p!^');
define('SECURE_AUTH_KEY',   '_SvykZEwn<K1Dj&L}p9h/$?A2wBMrvy=:=tbM<O(TU*),o/RDkN98~:4E+TOu>i_');
define('LOGGED_IN_KEY',     'sq8F8:L93R^T}h$2B~x|C>D,ww22T5I*D:4g`(Dm6L(GoG|FMCVql5`|>UgqMr=%');
define('NONCE_KEY',         '(QBo&zE[SG[xVj#_78PI^xkMq8n^6=YA[|dr)(M~Sj/1Pg*OHYnD|*j(+&Z*0@x0');
define('AUTH_SALT',         'wz_d6~BU?(&pHG?Mhi(wXc)<.0u+X%W$H_urVkl|/or0Cu7w{8+NP(6k>{7NHD8-');
define('SECURE_AUTH_SALT',  'P-2l6K^b`Tk[On{ttW^W940j8MT~)E}%!2aFnmnswp7F`8@ATcT]@Ld*XWTOR~7O');
define('LOGGED_IN_SALT',    '>be>9;>i%v=&M-wM#kt.?5i6&,Tx4U2B6)`v8q;<-)S}r-y*s3gfG:mCMb9X@z!l');
define('NONCE_SALT',        'Rj8<^yV$5]&-aK3K+Ll1Uz{0&Hr9wl:KvCt75P4KH<R0cQT8P&j&zD)3n657DqO{');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);
define('WP_DEBUG_LOG', false);




/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
